import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

import { parse, stringify } from "yaml";
import { z, type ZodType } from "zod";

import {
  createApiKeySchema,
  createCapsulePlanSchema,
  createCapsuleSchema,
  createCompressionSchema,
  createDecompressionSchema,
  createProjectSchema,
  createWebhookEndpointSchema,
  presignUploadSchema,
  problemSchema,
  rotateApiKeySchema,
  verifyCapsuleSchema,
} from "./index.js";

const repositoryRoot = fileURLToPath(new URL("../../../", import.meta.url));
const templatePath = fileURLToPath(
  new URL("../openapi.template.yaml", import.meta.url),
);
const apiSourcePath = `${repositoryRoot}apps/api/src/app.ts`;
const outputPath = `${repositoryRoot}docs/api/openapi.yaml`;

const generatedSchemas: Record<string, ZodType> = {
  ApiKeyCreate: createApiKeySchema,
  ApiKeyRotate: rotateApiKeySchema,
  PresignUpload: presignUploadSchema,
  CompressionCreate: createCompressionSchema,
  DecompressionCreate: createDecompressionSchema,
  WebhookCreate: createWebhookEndpointSchema,
  CapsulePlanCreate: createCapsulePlanSchema,
  CapsuleCreate: createCapsuleSchema,
  CapsuleVerify: verifyCapsuleSchema,
  Problem: problemSchema,
  ProjectCreate: createProjectSchema,
};

type OpenApiDocument = {
  paths: Record<string, Record<string, unknown>>;
  components: { schemas: Record<string, unknown> };
};

function requestSchema(schema: ZodType): Record<string, unknown> {
  const generated = z.toJSONSchema(schema, {
    io: "input",
    reused: "inline",
    cycles: "ref",
    unrepresentable: "any",
  }) as Record<string, unknown>;
  delete generated.$schema;
  return generated;
}

function operationsFromDocument(document: OpenApiDocument): Set<string> {
  const operations = new Set<string>();
  for (const [path, pathItem] of Object.entries(document.paths))
    for (const method of Object.keys(pathItem))
      if (["get", "post", "put", "patch", "delete"].includes(method))
        operations.add(`${method.toUpperCase()} ${path}`);
  return operations;
}

function operationsFromFastify(source: string): Set<string> {
  const operations = new Set<string>();
  const routePattern = /app\.(get|post|put|patch|delete)\(\s*"([^"]+)"/g;
  for (const match of source.matchAll(routePattern)) {
    const method = match[1];
    const path = match[2];
    if (method && path && path !== "/metrics")
      operations.add(`${method.toUpperCase()} ${path.replace(/:id/g, "{id}")}`);
  }
  return operations;
}

function assertSameOperations(
  document: OpenApiDocument,
  apiSource: string,
): void {
  const documented = operationsFromDocument(document);
  const implemented = operationsFromFastify(apiSource);
  const missing = [...implemented].filter(
    (operation) => !documented.has(operation),
  );
  const stale = [...documented].filter(
    (operation) => !implemented.has(operation),
  );
  if (missing.length || stale.length)
    throw new Error(
      `OpenAPI route inventory differs from Fastify: missing=[${missing.join(", ")}], stale=[${stale.join(", ")}]`,
    );
}

async function generate(): Promise<string> {
  const [template, apiSource] = await Promise.all([
    readFile(templatePath, "utf8"),
    readFile(apiSourcePath, "utf8"),
  ]);
  const document = parse(template) as OpenApiDocument;
  assertSameOperations(document, apiSource);
  delete document.components.schemas.Scope;
  for (const [name, schema] of Object.entries(generatedSchemas))
    document.components.schemas[name] = requestSchema(schema);
  return `# Generated by packages/schemas/src/generate-openapi.ts; do not edit directly.\n${stringify(document, { lineWidth: 0 })}`;
}

const generated = await generate();
if (process.argv.includes("--check")) {
  const current = await readFile(outputPath, "utf8").catch(() => "");
  if (current !== generated) {
    console.error("docs/api/openapi.yaml is stale; run pnpm openapi:generate");
    process.exitCode = 1;
  }
} else {
  await writeFile(outputPath, generated);
}
